### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by taskula** [Hypernova-Oy/redmine_private_email_support#1]
**Background**
We want to keep (most of) our Redmine projects publicly open. We also want to store all our support emails in Redmine so that it's easy for our employees to follow and search conversations. These emails cannot be publicly accessible.

Redmine offers a feature where a cronjob polls an IMAP server for incoming emails. If new emails are found with an existing issue ID in the email subject, a rake task creates a new comment into the issue using MailHandler class. See reference [1].

Step by step example:
1. A customer sends us an email
2. We reply to the email and append the email subject with e.g. [HN #123] where 123 is a Redmine issue id, and add our Redmine admin email as CC
3. Cron executes `redmine:email:receive_imap` task that reads Redmine admin email inbox and finds the email we sent in step 2
4. The task uses MailHandler class and adds a new comment to Redmine issue 123. The content of the comment contains the whole email body.

**The problem**
The problem is that these comments
1. are publicly visible
2. fill the issue comment section into an unreadable mess

**Feature Description**
Create a new plugin that extends above functionality.

Extend MailHandler class such that instead of adding the comment to issue id specified in email subject, create a new issue under a private project and create a relation between these two issues by adding a Related-to link (this is core Redmine functionality).

MailHandler takes a project id as a parameter. This project id should be our private project id.

Supposedly we also need a new rake task that uses this extension.

The feature then works step-by-step as follows:
1. A customer sends us an email
2. We reply to the email and amend the email subject with e.g. [HN #123] where 123 is a Redmine issue id, and add our Redmine admin email as CC
3. A task gets executed via cron and reads Redmine admin email inbox and finds the email we sent in step 2
4. The task uses our extended MailHandler class [2], creates a new issue titled "123 - <<original issue title>>" and adds a new comment to Redmine issue 999. The content of the comment contains the whole email body.
5. The task then creates a relation between issue 128 and 999 as follows:
![redmine_related_example](https://user-images.githubusercontent.com/12877644/73761563-b44f5600-4777-11ea-9ee1-e1b446425adc.jpg)

References
[1] https://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails
[2] https://github.com/redmine/redmine/blob/master/app/models/mail_handler.rb

**Comment by kivilahtio** [comment]
We discussed with Lari and we think that you can implement this feature simply by using unit tests. No need to set up SMTP infrastructure to test it out.
